name: Update Gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */8 * * *" # update every 8 hours
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: kylemocode/medium-stat-box@master
        env: 
          GH_PAT: ${{ secrets.GH_PAT }}
          MEDIUM_USER_NAME: ${{ secrets.MEDIUM_USER_NAME }}
          GIST_ID: ${{ secrets.GIST_ID }}
